#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace wwwroot.WXDataContext
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WXOA")]
	public partial class WXOADataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertTE_Department(TE_Department instance);
    partial void UpdateTE_Department(TE_Department instance);
    partial void DeleteTE_Department(TE_Department instance);
    partial void InsertTE_Duty(TE_Duty instance);
    partial void UpdateTE_Duty(TE_Duty instance);
    partial void DeleteTE_Duty(TE_Duty instance);
    #endregion
		
		public WXOADataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["WXOAConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public WXOADataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WXOADataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WXOADataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WXOADataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TE_Department> TE_Departments
		{
			get
			{
				return this.GetTable<TE_Department>();
			}
		}
		
		public System.Data.Linq.Table<TU_User> TU_Users
		{
			get
			{
				return this.GetTable<TU_User>();
			}
		}
		
		public System.Data.Linq.Table<TE_Duty> TE_Duties
		{
			get
			{
				return this.GetTable<TE_Duty>();
			}
		}
		
		public System.Data.Linq.Table<TE_DutyDetail> TE_DutyDetails
		{
			get
			{
				return this.GetTable<TE_DutyDetail>();
			}
		}
		
		public System.Data.Linq.Table<PLAN_Plan> PLAN_Plans
		{
			get
			{
				return this.GetTable<PLAN_Plan>();
			}
		}
		
		public System.Data.Linq.Table<PLAN_Appraise> PLAN_Appraises
		{
			get
			{
				return this.GetTable<PLAN_Appraise>();
			}
		}
		
		public System.Data.Linq.Table<PLAN_View1> PLAN_View1s
		{
			get
			{
				return this.GetTable<PLAN_View1>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TE_Departments")]
	public partial class TE_Department : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _CompanyId;
		
		private string _NO;
		
		private System.Nullable<int> _ParentID;
		
		private string _Name;
		
		private string _Tel;
		
		private string _Fax;
		
		private string _Address;
		
		private System.Nullable<int> _Sort;
		
		private string _Content;
		
		private System.Nullable<bool> _IsSubOrgan;
		
		private System.Nullable<System.Guid> _Host;
		
		private string _Assistants;
		
		private System.Nullable<System.Guid> _UpHost;
		
		private string _UpSubHosts;
		
		private string _SubHosts;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCompanyIdChanging(int value);
    partial void OnCompanyIdChanged();
    partial void OnNOChanging(string value);
    partial void OnNOChanged();
    partial void OnParentIDChanging(System.Nullable<int> value);
    partial void OnParentIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnTelChanging(string value);
    partial void OnTelChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnSortChanging(System.Nullable<int> value);
    partial void OnSortChanged();
    partial void OnContentChanging(string value);
    partial void OnContentChanged();
    partial void OnIsSubOrganChanging(System.Nullable<bool> value);
    partial void OnIsSubOrganChanged();
    partial void OnHostChanging(System.Nullable<System.Guid> value);
    partial void OnHostChanged();
    partial void OnAssistantsChanging(string value);
    partial void OnAssistantsChanged();
    partial void OnUpHostChanging(System.Nullable<System.Guid> value);
    partial void OnUpHostChanged();
    partial void OnUpSubHostsChanging(string value);
    partial void OnUpSubHostsChanged();
    partial void OnSubHostsChanging(string value);
    partial void OnSubHostsChanged();
    #endregion
		
		public TE_Department()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyId", DbType="Int NOT NULL")]
		public int CompanyId
		{
			get
			{
				return this._CompanyId;
			}
			set
			{
				if ((this._CompanyId != value))
				{
					this.OnCompanyIdChanging(value);
					this.SendPropertyChanging();
					this._CompanyId = value;
					this.SendPropertyChanged("CompanyId");
					this.OnCompanyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string NO
		{
			get
			{
				return this._NO;
			}
			set
			{
				if ((this._NO != value))
				{
					this.OnNOChanging(value);
					this.SendPropertyChanging();
					this._NO = value;
					this.SendPropertyChanged("NO");
					this.OnNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="Int")]
		public System.Nullable<int> ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					this.OnParentIDChanging(value);
					this.SendPropertyChanging();
					this._ParentID = value;
					this.SendPropertyChanged("ParentID");
					this.OnParentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="VarChar(50)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this.OnTelChanging(value);
					this.SendPropertyChanging();
					this._Tel = value;
					this.SendPropertyChanged("Tel");
					this.OnTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(50)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(50)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sort", DbType="Int")]
		public System.Nullable<int> Sort
		{
			get
			{
				return this._Sort;
			}
			set
			{
				if ((this._Sort != value))
				{
					this.OnSortChanging(value);
					this.SendPropertyChanging();
					this._Sort = value;
					this.SendPropertyChanged("Sort");
					this.OnSortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Content
		{
			get
			{
				return this._Content;
			}
			set
			{
				if ((this._Content != value))
				{
					this.OnContentChanging(value);
					this.SendPropertyChanging();
					this._Content = value;
					this.SendPropertyChanged("Content");
					this.OnContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSubOrgan", DbType="Bit")]
		public System.Nullable<bool> IsSubOrgan
		{
			get
			{
				return this._IsSubOrgan;
			}
			set
			{
				if ((this._IsSubOrgan != value))
				{
					this.OnIsSubOrganChanging(value);
					this.SendPropertyChanging();
					this._IsSubOrgan = value;
					this.SendPropertyChanged("IsSubOrgan");
					this.OnIsSubOrganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Host", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> Host
		{
			get
			{
				return this._Host;
			}
			set
			{
				if ((this._Host != value))
				{
					this.OnHostChanging(value);
					this.SendPropertyChanging();
					this._Host = value;
					this.SendPropertyChanged("Host");
					this.OnHostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Assistants", DbType="NVarChar(200)")]
		public string Assistants
		{
			get
			{
				return this._Assistants;
			}
			set
			{
				if ((this._Assistants != value))
				{
					this.OnAssistantsChanging(value);
					this.SendPropertyChanging();
					this._Assistants = value;
					this.SendPropertyChanged("Assistants");
					this.OnAssistantsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpHost", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UpHost
		{
			get
			{
				return this._UpHost;
			}
			set
			{
				if ((this._UpHost != value))
				{
					this.OnUpHostChanging(value);
					this.SendPropertyChanging();
					this._UpHost = value;
					this.SendPropertyChanged("UpHost");
					this.OnUpHostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpSubHosts", DbType="NVarChar(200)")]
		public string UpSubHosts
		{
			get
			{
				return this._UpSubHosts;
			}
			set
			{
				if ((this._UpSubHosts != value))
				{
					this.OnUpSubHostsChanging(value);
					this.SendPropertyChanging();
					this._UpSubHosts = value;
					this.SendPropertyChanged("UpSubHosts");
					this.OnUpSubHostsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubHosts", DbType="NVarChar(200)")]
		public string SubHosts
		{
			get
			{
				return this._SubHosts;
			}
			set
			{
				if ((this._SubHosts != value))
				{
					this.OnSubHostsChanging(value);
					this.SendPropertyChanging();
					this._SubHosts = value;
					this.SendPropertyChanged("SubHosts");
					this.OnSubHostsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TU_Users")]
	public partial class TU_User
	{
		
		private System.Guid _UserID;
		
		private int _CompanyID;
		
		private System.Nullable<int> _DepartmentID;
		
		private System.Nullable<int> _DutyId;
		
		private string _RealName;
		
		private System.Nullable<int> _State;
		
		private System.Nullable<int> _Grade;
		
		private System.Nullable<bool> _ArchiveBySelf;
		
		private System.Nullable<System.DateTime> _EditTime;
		
		public TU_User()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyID", DbType="Int NOT NULL")]
		public int CompanyID
		{
			get
			{
				return this._CompanyID;
			}
			set
			{
				if ((this._CompanyID != value))
				{
					this._CompanyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentID", DbType="Int")]
		public System.Nullable<int> DepartmentID
		{
			get
			{
				return this._DepartmentID;
			}
			set
			{
				if ((this._DepartmentID != value))
				{
					this._DepartmentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DutyId", DbType="Int")]
		public System.Nullable<int> DutyId
		{
			get
			{
				return this._DutyId;
			}
			set
			{
				if ((this._DutyId != value))
				{
					this._DutyId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealName", DbType="NVarChar(50)")]
		public string RealName
		{
			get
			{
				return this._RealName;
			}
			set
			{
				if ((this._RealName != value))
				{
					this._RealName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="Int")]
		public System.Nullable<int> State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grade", DbType="Int")]
		public System.Nullable<int> Grade
		{
			get
			{
				return this._Grade;
			}
			set
			{
				if ((this._Grade != value))
				{
					this._Grade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArchiveBySelf", DbType="Bit")]
		public System.Nullable<bool> ArchiveBySelf
		{
			get
			{
				return this._ArchiveBySelf;
			}
			set
			{
				if ((this._ArchiveBySelf != value))
				{
					this._ArchiveBySelf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> EditTime
		{
			get
			{
				return this._EditTime;
			}
			set
			{
				if ((this._EditTime != value))
				{
					this._EditTime = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TE_Duties")]
	public partial class TE_Duty : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _ID;
		
		private int _CompanyID;
		
		private string _NO;
		
		private string _Name;
		
		private string _Menus;
		
		private System.Nullable<int> _GradeID;
		
		private string _DeptPos;
		
		private System.Nullable<int> _DutyCatagoryID;
		
		private string _Description;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(short value);
    partial void OnIDChanged();
    partial void OnCompanyIDChanging(int value);
    partial void OnCompanyIDChanged();
    partial void OnNOChanging(string value);
    partial void OnNOChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnMenusChanging(string value);
    partial void OnMenusChanged();
    partial void OnGradeIDChanging(System.Nullable<int> value);
    partial void OnGradeIDChanged();
    partial void OnDeptPosChanging(string value);
    partial void OnDeptPosChanged();
    partial void OnDutyCatagoryIDChanging(System.Nullable<int> value);
    partial void OnDutyCatagoryIDChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public TE_Duty()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyID", DbType="Int NOT NULL")]
		public int CompanyID
		{
			get
			{
				return this._CompanyID;
			}
			set
			{
				if ((this._CompanyID != value))
				{
					this.OnCompanyIDChanging(value);
					this.SendPropertyChanging();
					this._CompanyID = value;
					this.SendPropertyChanged("CompanyID");
					this.OnCompanyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NO", DbType="VarChar(10)")]
		public string NO
		{
			get
			{
				return this._NO;
			}
			set
			{
				if ((this._NO != value))
				{
					this.OnNOChanging(value);
					this.SendPropertyChanging();
					this._NO = value;
					this.SendPropertyChanged("NO");
					this.OnNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Menus", DbType="NVarChar(MAX)")]
		public string Menus
		{
			get
			{
				return this._Menus;
			}
			set
			{
				if ((this._Menus != value))
				{
					this.OnMenusChanging(value);
					this.SendPropertyChanging();
					this._Menus = value;
					this.SendPropertyChanged("Menus");
					this.OnMenusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeID", DbType="Int")]
		public System.Nullable<int> GradeID
		{
			get
			{
				return this._GradeID;
			}
			set
			{
				if ((this._GradeID != value))
				{
					this.OnGradeIDChanging(value);
					this.SendPropertyChanging();
					this._GradeID = value;
					this.SendPropertyChanged("GradeID");
					this.OnGradeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeptPos", DbType="VarChar(20)")]
		public string DeptPos
		{
			get
			{
				return this._DeptPos;
			}
			set
			{
				if ((this._DeptPos != value))
				{
					this.OnDeptPosChanging(value);
					this.SendPropertyChanging();
					this._DeptPos = value;
					this.SendPropertyChanged("DeptPos");
					this.OnDeptPosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DutyCatagoryID", DbType="Int")]
		public System.Nullable<int> DutyCatagoryID
		{
			get
			{
				return this._DutyCatagoryID;
			}
			set
			{
				if ((this._DutyCatagoryID != value))
				{
					this.OnDutyCatagoryIDChanging(value);
					this.SendPropertyChanging();
					this._DutyCatagoryID = value;
					this.SendPropertyChanged("DutyCatagoryID");
					this.OnDutyCatagoryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TE_DutyDetail")]
	public partial class TE_DutyDetail
	{
		
		private long _ID;
		
		private string _Name;
		
		private System.Nullable<int> _Persons;
		
		private string _UsersName;
		
		private System.Nullable<int> _DepartentID;
		
		private System.Nullable<int> _DutyID;
		
		private System.Nullable<int> _DutyCatagoryID;
		
		private System.Nullable<System.DateTime> _Addtime;
		
		private System.Nullable<int> _GradeID;
		
		public TE_DutyDetail()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(200)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Persons", DbType="Int")]
		public System.Nullable<int> Persons
		{
			get
			{
				return this._Persons;
			}
			set
			{
				if ((this._Persons != value))
				{
					this._Persons = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsersName", DbType="VarChar(8000)")]
		public string UsersName
		{
			get
			{
				return this._UsersName;
			}
			set
			{
				if ((this._UsersName != value))
				{
					this._UsersName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartentID", DbType="Int")]
		public System.Nullable<int> DepartentID
		{
			get
			{
				return this._DepartentID;
			}
			set
			{
				if ((this._DepartentID != value))
				{
					this._DepartentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DutyID", DbType="Int")]
		public System.Nullable<int> DutyID
		{
			get
			{
				return this._DutyID;
			}
			set
			{
				if ((this._DutyID != value))
				{
					this._DutyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DutyCatagoryID", DbType="Int")]
		public System.Nullable<int> DutyCatagoryID
		{
			get
			{
				return this._DutyCatagoryID;
			}
			set
			{
				if ((this._DutyCatagoryID != value))
				{
					this._DutyCatagoryID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Addtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> Addtime
		{
			get
			{
				return this._Addtime;
			}
			set
			{
				if ((this._Addtime != value))
				{
					this._Addtime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeID", DbType="Int")]
		public System.Nullable<int> GradeID
		{
			get
			{
				return this._GradeID;
			}
			set
			{
				if ((this._GradeID != value))
				{
					this._GradeID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PLAN_Plan")]
	public partial class PLAN_Plan
	{
		
		private int _id;
		
		private string _Title;
		
		private System.Nullable<int> _Total;
		
		private System.Nullable<int> _Current;
		
		private System.Nullable<System.Guid> _UserID;
		
		private System.Nullable<int> _DepartmentID;
		
		private string _Content;
		
		private string _Summary;
		
		private string _Appraise;
		
		private System.Nullable<int> _Type;
		
		private System.Nullable<int> _RangeType;
		
		private System.Nullable<System.DateTime> _Starttime;
		
		private System.Nullable<System.DateTime> _Stoptime;
		
		private System.Nullable<System.DateTime> _Addtime;
		
		private System.Nullable<int> _PlanState;
		
		private string _Reason;
		
		private string _DateKey;
		
		public PLAN_Plan()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(2000)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Int")]
		public System.Nullable<int> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Current]", Storage="_Current", DbType="Int")]
		public System.Nullable<int> Current
		{
			get
			{
				return this._Current;
			}
			set
			{
				if ((this._Current != value))
				{
					this._Current = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentID", DbType="Int")]
		public System.Nullable<int> DepartmentID
		{
			get
			{
				return this._DepartmentID;
			}
			set
			{
				if ((this._DepartmentID != value))
				{
					this._DepartmentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Content
		{
			get
			{
				return this._Content;
			}
			set
			{
				if ((this._Content != value))
				{
					this._Content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Summary", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Summary
		{
			get
			{
				return this._Summary;
			}
			set
			{
				if ((this._Summary != value))
				{
					this._Summary = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Appraise", DbType="VarChar(2000)")]
		public string Appraise
		{
			get
			{
				return this._Appraise;
			}
			set
			{
				if ((this._Appraise != value))
				{
					this._Appraise = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int")]
		public System.Nullable<int> Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RangeType", DbType="Int")]
		public System.Nullable<int> RangeType
		{
			get
			{
				return this._RangeType;
			}
			set
			{
				if ((this._RangeType != value))
				{
					this._RangeType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Starttime", DbType="DateTime")]
		public System.Nullable<System.DateTime> Starttime
		{
			get
			{
				return this._Starttime;
			}
			set
			{
				if ((this._Starttime != value))
				{
					this._Starttime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stoptime", DbType="DateTime")]
		public System.Nullable<System.DateTime> Stoptime
		{
			get
			{
				return this._Stoptime;
			}
			set
			{
				if ((this._Stoptime != value))
				{
					this._Stoptime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Addtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> Addtime
		{
			get
			{
				return this._Addtime;
			}
			set
			{
				if ((this._Addtime != value))
				{
					this._Addtime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanState", DbType="Int")]
		public System.Nullable<int> PlanState
		{
			get
			{
				return this._PlanState;
			}
			set
			{
				if ((this._PlanState != value))
				{
					this._PlanState = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reason", DbType="VarChar(5000)")]
		public string Reason
		{
			get
			{
				return this._Reason;
			}
			set
			{
				if ((this._Reason != value))
				{
					this._Reason = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateKey", DbType="VarChar(10)")]
		public string DateKey
		{
			get
			{
				return this._DateKey;
			}
			set
			{
				if ((this._DateKey != value))
				{
					this._DateKey = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PLAN_Appraise")]
	public partial class PLAN_Appraise
	{
		
		private int _id;
		
		private int _PlanID;
		
		private System.Nullable<int> _Appraise;
		
		private string _Content;
		
		private System.Nullable<System.Guid> _UserID;
		
		private System.Nullable<System.DateTime> _AddTime;
		
		public PLAN_Appraise()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanID", DbType="Int NOT NULL")]
		public int PlanID
		{
			get
			{
				return this._PlanID;
			}
			set
			{
				if ((this._PlanID != value))
				{
					this._PlanID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Appraise", DbType="Int")]
		public System.Nullable<int> Appraise
		{
			get
			{
				return this._Appraise;
			}
			set
			{
				if ((this._Appraise != value))
				{
					this._Appraise = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="VarChar(500)")]
		public string Content
		{
			get
			{
				return this._Content;
			}
			set
			{
				if ((this._Content != value))
				{
					this._Content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> AddTime
		{
			get
			{
				return this._AddTime;
			}
			set
			{
				if ((this._AddTime != value))
				{
					this._AddTime = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PLAN_View1")]
	public partial class PLAN_View1
	{
		
		private int _id;
		
		private System.Nullable<System.Guid> _UserID;
		
		private System.Nullable<int> _Type;
		
		private System.Nullable<int> _RangeType;
		
		private System.Nullable<System.DateTime> _Starttime;
		
		private string _Content;
		
		private System.Nullable<System.Guid> _Expr1;
		
		public PLAN_View1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int")]
		public System.Nullable<int> Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RangeType", DbType="Int")]
		public System.Nullable<int> RangeType
		{
			get
			{
				return this._RangeType;
			}
			set
			{
				if ((this._RangeType != value))
				{
					this._RangeType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Starttime", DbType="DateTime")]
		public System.Nullable<System.DateTime> Starttime
		{
			get
			{
				return this._Starttime;
			}
			set
			{
				if ((this._Starttime != value))
				{
					this._Starttime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="VarChar(500)")]
		public string Content
		{
			get
			{
				return this._Content;
			}
			set
			{
				if ((this._Content != value))
				{
					this._Content = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expr1", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> Expr1
		{
			get
			{
				return this._Expr1;
			}
			set
			{
				if ((this._Expr1 != value))
				{
					this._Expr1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
